const data = {
  products: [
    {
      name: 'Nike Shirt',
      slug: 'nike-shirt',
      category: 'Shirts',
      image: '/images/shirt1.jpg',
      price: 700000,
      brand: 'Nike',
      rating: 4.4,
      numReviews: 8,
      countInStock: 20,
      description: 'A breath able shirt',
      isFeatured: true,
      banner: '/images/banner1.jpg',
    },
    {
      name: 'Adidas Shirt',
      slug: 'adidas-shirt',
      category: 'Shirts',
      image: '/images/shirt2.jpg',
      price: 900000,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 18,
      countInStock: 20,
      description: 'A breath able shirt',
      isFeatured: true,
      banner: '/images/banner2.jpg',
    },
    {
      name: 'Puma Shirt',
      slug: 'puma-shirt',
      category: 'Shirts',
      image: '/images/shirt3.jpg',
      price: 500000,
      brand: 'Puma',
      rating: 3.8,
      numReviews: 5,
      countInStock: 20,
      description: 'A breath able shirt',
    },
    {
      name: 'Kappa Pants',
      slug: 'kappa-pants',
      category: 'Pants',
      image: '/images/pants1.jpg',
      price: 150000,
      brand: 'Kappa',
      rating: 4.1,
      numReviews: 13,
      countInStock: 20,
      description: 'A breath able shirt',
    },
    {
      name: 'Diadora Pants',
      slug: 'diadora-pants',
      category: 'Pants',
      image: '/images/pants2.jpg',
      price: 220000,
      brand: 'Diadora',
      rating: 4.0,
      numReviews: 5,
      countInStock: 20,
      description: 'A breath able shirt',
    },
    {
      name: 'Asics Pants',
      slug: 'asics-pants',
      category: 'Pants',
      image: '/images/pants3.jpg',
      price: 330000,
      brand: 'Asics',
      rating: 4.3,
      numReviews: 5,
      countInStock: 20,
      description: 'A breath able shirt',
    },
  ],
};

export default data;
